server:
  port: 8080
spring:
  application:
    name: online-ticket-sales
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/online_ticket_sales_db?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    compatibility-verifier:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: tanthanh.060918@gmail.com
    password: xvdl vnek mpqm dbzn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cloudinary:
    cloudName: ${CLOUDINARY_CLOUD_NAME}
    apiKey: ${CLOUDINARY_API_KEY}
    apiSecret: ${CLOUDINARY_API_SECRET}


outbound:
  identity:
    client-id: ${OAUTH_GOOGLE_CLIENT_ID}
    client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
    redirect-uri: "http://localhost:5173/authenticate"

management:
  endpoints:
    web:
      exposure:
        include: '*'
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
open:
  api:
    title: API document
    version: v1.0.0
    description: API Service
    serverUrl: http://localhost:8080
    serverName: Server
    license: https://github.com/gahoccode215/Summer2025_SBA301_2

logging:
  level:
    root: INFO
    web: INFO

jwt:
  expiryHour: 1
  expiryDay: 14
  accessKey: c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=
  refreshKey: 9k1jJAWAKQCnCEz1pwcPNegbHoLugf9hgEnn6sz5pFc=
  resetKey: 2OeEeG48CvIcH1K0UAXbSo/7gPj3QLJ7MnQZuscRirQ=

rabbitmq:
  exchangeName: sba.exchange
  user-mail-queue: userMailQueue
  user-mail-routing-key: userMailQueueRoutingKey

app:
  defaultImage: https://media.licdn.com/dms/image/v2/C5112AQEw1fXuabCTyQ/article-inline_image-shrink_1500_2232/article-inline_image-shrink_1500_2232/0/1581099611064?e=1755129600&v=beta&t=uOI9KdstVt77LeFfmofOTwfgEbtAZ3LyR3aLwR70slw

vnpay:
  tmn-code: ${VNP_TMN_CODE}
  hash-secret: ${VNP_HASHSECRET}
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  return-url: http://localhost:5173/payments/success
  version: 2.1.0
  command: pay
  order-type: other
  currency-code: VND
